author/views.py
from flask import Blueprint, request, render_template, url_for,session, redirect, flash
from werkzeug.security import generate_password_hash
from urllib.parse import urlparse
from urllib.parse import urljoin
from opencage.geocoder import OpenCageGeocode
from urllib.request import urlopen
import json

from author.models import Author
from author.forms import RegisterForm, LoginForm, AddressForm
from application import db
from author.decorators import login_required

author_app = Blueprint("author_app", __name__)

key = '2d4978b63c7f451fa89976d4bb779136'
geocoder = OpenCageGeocode(key)

class Place(object):
  def meters_to_walking_time(self, meters):
      return int(meters / 80)

  def wiki_path(self, slug):
      return urljoin( 'http://en.wikipedia.org/wiki/', slug.replace(' ', '_'))

  def address_to_latlng(self, address):
      results = geocoder.geocode(address)
      lat = results[0]['geometry']['lat']
      lng = results[0]['geometry']['lng']

      return (lat, lng)

  def query(self, address):

    results = geocoder.geocode(address)
    lat = results[0]['geometry']['lat']
    lng = results[0]['geometry']['lng']

    query_url = 'https://en.wikipedia.org/w/api.php?action=query&list=geosearch&gscoord={0}%7C{1}&gsradius=5000&gslimit=20&format=json'.format(lat, lng)
    g = urlopen(query_url)

    results = g.read()

    g.close()

    data = json.loads(results)

    places = []
    for place in data['query']['geosearch']:
      name = place['title']
      meters = place['dist']
      lat = place['lat']
      lng = place['lon']

      wiki_url = self.wiki_path(name)
      walking_time = self.meters_to_walking_time(meters)

      d = {
        'name': name,
        'url': wiki_url,
        'time': walking_time,
        'lat': lat,
        'lng': lng
      }

      places.append(d)

    return places




@author_app.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(
        form.full_name.data,
        form.email.data,
        hashed_password
        )
        db.session.add(author)
        db.session.commit()
        flash("You have successfully registered", "success")
        return render_template("author/login.html", form=form)
    return render_template("author/register.html", form=form)

@author_app.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm()
    error = None

    if request.method == "GET" and request.args.get("next"):
        session["next"] = request.args.get("next", None)
    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session['id'] = author.id
        session['full_name'] = author.full_name
        if 'next' in session:
            next = session.get('next')
            session.pop('next')
            return redirect(next)
        else:
            return redirect(url_for("blog_app.index"))

    return render_template("author/login.html", form=form, error = error)

@author_app.route('/geo_location', methods=['GET','POST'])
@login_required
def geo_location():
    form = AddressForm()

    places = []

    my_coordinates = (37.4221,-122.08)

    if request.method == "POST" :
        if form.validate() == False:
            return render_template("author/geo.html", form= form)
        else:
            address = form.address.data

            p = Place()
            my_coordinates = p.address_to_latlng(address)
            places = p.query(address)

            return render_template("author/geo.html", form=form, my_coordinates = my_coordinates, places=places)

    return render_template("author/geo.html", form= form, my_coordinates=my_coordinates, places=places, geo = True)


@author_app.route('/logout')
def logout():
    session.pop ("id")
    session.pop("full_name")
    flash("You have been successfully logged out ", "success")
    return redirect(url_for(".login"))

blog/views.py
from flask import Blueprint,render_template,flash,redirect,url_for,request, session
from slugify import slugify
import uuid
import os
from PIL import Image

from application import db
from blog.models import Post, Category, Tag
from blog.forms import PostForm
from author.models import Author
from author.decorators import login_required
from settings import BLOG_POST_IMAGES_PATH

blog_app = Blueprint("blog_app",__name__)

POSTS_PER_PAGE = 7

@blog_app.route('/')
def index():
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(live=True).order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('index.html', posts=posts,title="Latest Posts")

@blog_app.route('/post', methods=("GET", "POST"))
@login_required
def post():
    form = PostForm()
    tags_field = request.values.get('tags_field', '')


    if form.validate_on_submit():
        image_id = None

        if form.image.data:
            # process image
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.png'
            file_path = os.path.join(
                BLOG_POST_IMAGES_PATH, file_name
            )
            im = Image.open(f,"r")
            im.save(file_path)

            # create sizes
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, 'lg')
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 300, 'sm')


        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            category = new_category
        else:
            category = form.category.data
        author = Author.query.get(session['id'])
        title = form.title.data.strip()
        body = form.body.data.strip()
        post = Post(
        author=author,
        title=title,
        body=body,
        image = image_id,
        category=category
        )

        _save_tags(post,tags_field)

        db.session.add(post)
        db.session.commit()

        slug = slugify(str(post.id) + "-" + post.title)
        post.slug = slug
        db.session.commit()
        flash("Article has been Posted", "success")
        return redirect(url_for('.article', slug=slug))


    return render_template("blog/post.html", form=form, action = 'new', tags_field = tags_field)

@blog_app.route('/posts/<slug>')
def article(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template('blog/article.html', post=post)

@blog_app.route('/edit/<slug>', methods=('GET', 'POST'))
@login_required
def edit(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    form = PostForm(obj=post)
    tags_field = request.values.get('tags_field', _load_tags_field(post))

    if form.validate_on_submit():
        original_image = post.image
        original_title = post.title
        form.populate_obj(post)

        if form.image.data:
            # process image
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.png'
            file_path = os.path.join(
                BLOG_POST_IMAGES_PATH, file_name
            )
            Image.open(f).save(file_path)

            # create sizes
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, 'lg')
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 300, 'sm')

            post.image = image_id
        else:
            post.image = original_image

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            post.category = new_category

        # update slug if title changed
        if form.title.data != original_title:
            post.slug = slugify(str(post.id) + '-' + form.title.data)

        # process tags
        _save_tags(post, tags_field)

        db.session.commit()
        flash('Article edited')
        return redirect(url_for('.article', slug=post.slug))

    return render_template('blog/post.html',
        form=form,
        post=post,
        action="edit",
        tags_field=tags_field
    )

@blog_app.route('/delete/<slug>')
@login_required
def delete(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    post.live = False
    db.session.commit()
    flash("Article deleted")
    return redirect(url_for('.index'))

@blog_app.route('/categories/<category_id>')
def categories(category_id):
    category = Category.query.filter_by(id=category_id).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(category=category, live=True)\
        .order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/category_posts.html',
        posts=posts,
        title=category,
        category_id=category_id
    )
@blog_app.route('/tags/<tag>')
def tags(tag):
    tag = Tag.query.filter_by(name=tag).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = tag.posts.filter_by(live=True)\
        .order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/tag_posts.html',
        posts=posts,
        title="Tag: " + str(tag),
        tag=str(tag)
    )


def _image_resize(original_file_path,image_id, image_base, extension):
    file_path = os.path.join(
        original_file_path, image_id + '.png'
    )
    image = Image.open(file_path)
    wpercent = (image_base / float(image.size[0]))
    hsize = int((float(image.size[1]) * float(wpercent)))
    image = image.resize((image_base, hsize), Image.ANTIALIAS)
    modified_file_path = os.path.join(
        original_file_path, image_id + '.' + extension + '.png'
    )
    image.save(modified_file_path)
    return

def _save_tags(post, tags_field):
    post.tags.clear()
    for tag_item in tags_field.split(','):
        tag = Tag.query.filter_by(name=slugify(tag_item)).first()
        if not tag:
            tag = Tag(name=slugify(tag_item))
            db.session.add(tag)
        post.tags.append(tag)
    return post

def _load_tags_field(post):
    tags_field = '';
    for tag in post.tags:
        tags_field += tag.name + ', '
    return tags_field[:-2]

templates/_flashmessages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="messages">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endwith %}

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/bootstrap.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/font-awesome.min.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/owl.carousel.min.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/owl.theme.default.min.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="style.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="responsive.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/main.css")}}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
 integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
 crossorigin=""></script>
    <title>{% block title %}{% endblock %}</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  </head>
  <body>

    {% block nav %}{% endblock %}

    <div class="container">

    {% block content %}{% endblock %}

    <div class="offset-md-2 col-md-8 pt-5 pb-3">
      <footer>
        <span class="text-muted">&copy; 2020 {{ config['BLOG_NAME'] }}</span>
        <span class="text-muted">Developed and Designed By Rajan Rajesh Mishra</span>
      </footer>
    </div>

    </div>

    <!-- bootstrap -->
    <script src="{{ url_for ("static", filename="js/jquery-3.1.1.min.js")}}"></script>
    <script src="{{ url_for ("static", filename="js/bootstrap.min.js")}}"></script>
    <script src="{{ url_for ("static", filename="js/owl.carousel.min.js")}}"></script>
    <script src="{{ url_for ("static", filename="js/active.js")}}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/bootstrap.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/font-awesome.min.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/owl.carousel.min.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/owl.theme.default.min.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="style.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="responsive.css")}}">
    <link rel="stylesheet" href="{{ url_for ("static", filename="css/main.css")}}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
 integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
 crossorigin=""></script>
    <title>{% block title %}{% endblock %}</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>

<body>
    <div class="wrapper">
        <header class="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-2">
                        <div class="logo">
                            <h2><a class="navbar-brand" href="{{ url_for('blog_app.index') }}">
                                {{ config['BLOG_NAME'] }}
                              </a></h2>
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div class="menu">
                            <ul>
                                {% if session.id %}
                                <li><span class="navbar-text text-dark">{{ session.full_name }}</span></li>
                                <li><a href=""{{ url_for('blog_app.index') }}">Home</a></li>
                                <li><a class="nav-link" href="{{ url_for('blog_app.post')}}">New Post</a></li>
                                <li><a class="nav-link" href="{{ url_for('author_app.logout')}}">Logout</a></li>
                                <li><a class="nav-link" href="{{ url_for('author_app.geo_location')}}">Geo-Location</a></li>
                                {% else %}
                                <li><a class="nav-link" href="{{ url_for('author_app.login')}}">Login</a></li>
                                <li><a class="nav-link" href="{{ url_for('author_app.register')}}">SignUp</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section class="bg-text-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="bg-text">
                            <h3>{{ config['BLOG_NAME'] }}</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="blog-post-area">
            <div class="container">

                <div class="row">
                    {% for post in posts.items %}
                            <div class="col-md-3">
                                <div class="single-post">
                                    {% if post.image %}
                                        <img src="{{ url_for('static', filename='images/uploads/' + post.image + '.sm.png') }}" class="img-thumbnail" />
                                    {% endif %}
                                    <h3><a href="{{ url_for('blog_app.article', slug=post.slug) }}">{{ post.title }}</a></h3>
                                    <h4><span>Posted by {{ post.author.full_name }}</span>
                                    </h4>
                                    <p>{{ post.body[:220] }}</p>
                                    <h4><span>{{ post.publish_date.strftime('%Y-%m-%d') }}
                                        {% if post.category %}
                                        in <a href="{{ url_for('.categories', category_id=post.category.id )}}">
                                        {{ post.category.name }}
                                        </a>
                                        {% endif %}
                                    </span></h4>
                                </div>
                            </div>
                            {% endfor %}
                    </div>

                </div>

            <div class="pegination">
                <!--
                <ul>
                    <li><i class="fa fa-angle-left" aria-hidden="true"></i></li>
                    <li class="active">1</li>
                    <li>2</li>
                    <li>3</li>
                    <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
                </ul>
-->

                <div class="nav-links">
                    {% if posts.has_prev %}
                    <a href="{{ url_for('blog_app.index', page=posts.prev_num) }}">&lt;&lt; Newer posts</a>
                  {% endif %}
                  {% if posts.has_next %}
                    <a href="{{ url_for('blog_app.index', page=posts.next_num) }}">Older posts &gt;&gt;</a>
                  {% endif %}
                </div>
            </div>
        </section>

        <div class="offset-md-2 col-md-8 pt-5 pb-3">
          <footer>
            <span class="text-muted">&copy; 2020 {{ config['BLOG_NAME'] }}</span>
            <span class="text-muted">Developed and Designed By Rajan Rajesh Mishra</span>
          </footer>
        </div>

        </div>
    </div>




    <script src="{{ url_for ("static", filename="js/jquery-3.1.1.min.js")}}"></script>
    <script src="{{ url_for ("static", filename="js/bootstrap.min.js")}}"></script>
    <script src="{{ url_for ("static", filename="js/owl.carousel.min.js")}}"></script>
    <script src="{{ url_for ("static", filename="js/active.js")}}"></script>
</body>

</html>

templates/nav.html
<div class="wrapper">
  <header class="header">
      <div class="container">
          <div class="row">
              <div class="col-md-2">
                  <div class="logo">
                      <h2><a class="navbar-brand" href="{{ url_for('blog_app.index') }}">
                          {{ config['BLOG_NAME'] }}
                        </a></h2>
                  </div>
              </div>
              <div class="col-md-10">
                  <div class="menu">
                      <ul>
                          {% if session.id %}
                          <li><span class="navbar-text text-dark">{{ session.full_name }}</span></li>
                          <li><a href="{{ url_for('blog_app.index') }}">Home</a></li>
                          <li><a class="nav-link" href="{{ url_for('blog_app.post')}}">New Post</a></li>
                          <li><a class="nav-link" href="{{ url_for('author_app.logout')}}">Logout</a></li>
                          <li><a class="nav-link" href="{{ url_for('author_app.geo_location')}}">Geo-Location</a></li>
                          {% else %}
                          <li><a class="nav-link" href="{{ url_for('author_app.login')}}">Login</a></li>
                          <li><a class="nav-link" href="{{ url_for('author_app.register')}}">SignUp</a></li>
                          {% endif %}
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </header>